language: cpp
compiler:
  - gcc
env:
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -o Dir::Etc::sourcelist="sources.list.d/ubuntu-toolchain-r-test-$(lsb_release -c -s).list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
  - git clone https://github.com/zeromq/libzmq.git
  - wget -q -O- https://github.com/zeromq/czmq/archive/v3.0.2.tar.gz | tar pxz && mv czmq-3.0.2 czmq
  - export LD_LIBRARY_PATH=.:`cat /etc/ld.so.conf.d/* | grep -vF "#" | tr "\\n" ":" | sed -e "s/:$//g"`
install:
  - sudo apt-get install -y -qq autoconf automake libtool make gcc-4.9 g++-4.9 lcov libcurl4-openssl-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 90
  - pushd libzmq && ./autogen.sh && ./configure --without-libsodium --without-documentation --without-vmci && make -j4 && sudo make install && popd
  - pushd czmq && ./autogen.sh && ./configure && make -j4 && sudo make install && popd
before_script:
script:
  ./autogen.sh && ./configure --enable-coverage && make test -j4
after_failure:
  - cat config.log
  - cat test/*.log
